/*
  # Import 37 Prospects from CSV - Final Version
  
  Imports all prospects with 2 closed sales
*/

DO $$
DECLARE v_org UUID:='a0000000-0000-0000-0000-000000000001'; v_adm UUID:='ace4a9eb-0437-482c-8012-a7f8f977b324'; c UUID; p UUID;
BEGIN
  SELECT id INTO p FROM plan_catalog WHERE plan_catalog.org_id=v_org LIMIT 1;
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'','','981252424','otro','cotizado','2026-03-11') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','envio_cotizacion','Pilar - Excellent/Confort','2026-03-11');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'','','984106122','otro','prospecto','2026-03-11') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','Itauguá','2026-03-11');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Sandri','','983282969','otro','prospecto','2026-03-11') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','Saludo inicial','2026-03-11');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Elizabet','','992587495','otro','cotizado','2026-03-11') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','envio_cotizacion','San Lorenzo - Suegra 69 años','2026-03-11');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Abner','Smith','976655776','otro','prospecto','2026-03-12') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','','2026-03-12');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'','','992653669','otro','prospecto','2026-03-12') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','','2026-03-12');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Nancy','','992396645','otro','cotizado','2026-03-12') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','envio_cotizacion','Capiatá - Mujer 42','2026-03-12');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Antonio Fabián','Stefani','991208869','otro','cotizado','2026-03-13') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','envio_cotizacion','Fernando - Pareja + hijo','2026-03-13');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Gustavo','Rojas','983864392','whatsapp','prospecto','2026-03-15') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'whatsapp','contacto_inicial','','2026-03-15');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'','','983360339','whatsapp','prospecto','2026-03-16') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'whatsapp','contacto_inicial','','2026-03-16');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'','','991340640','otro','cotizado','2026-03-16') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','envio_cotizacion','Confort/Quality/Excellent','2026-03-16');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Loryn','Figueredo','982443944','otro','cotizado','2026-03-16') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','envio_cotizacion','Familia 3','2026-03-16');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Belén','Vila','982111099','otro','cotizado','2026-03-16') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','envio_cotizacion','Mujer titular','2026-03-16');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Eduardo','González','993233579','otro','prospecto','2026-03-18') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','','2026-03-18');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'','','986337491','otro','prospecto','2026-03-18') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','','2026-03-18');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Sofía','','981382420','otro','cotizado','2026-03-18') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','envio_cotizacion','Adulto Mayor','2026-03-18');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Romina','','983855247','otro','activo','2026-03-27') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','Confort contratado','2026-03-18'); INSERT INTO client_plans (org_id,client_id,agent_id,plan_catalog_id,plan_tier,status,monthly_premium,annual_premium,commission_pct,start_date,num_beneficiaries) VALUES (v_org,c,v_adm,p,'confort','activo',39000,468000,15.00,'2026-03-27',1);
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'','','981135602','otro','prospecto','2026-03-19') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','','2026-03-19');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Wilberto','Otazu','985889298','otro','cotizado','2026-03-19') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','envio_cotizacion','Familia 4','2026-03-19');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'','','976666213','otro','prospecto','2026-03-20') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','','2026-03-20');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Javier','Mora','971561877','otro','cotizado','2026-03-21') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','envio_cotizacion','Padre 67','2026-03-21');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Víctor','Rivas','981863780','otro','activo','2026-03-26') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','Excellent familia 6','2026-03-22'); INSERT INTO client_plans (org_id,client_id,agent_id,plan_catalog_id,plan_tier,status,monthly_premium,annual_premium,commission_pct,start_date,num_beneficiaries) VALUES (v_org,c,v_adm,p,'excellent','activo',200083,2401000,15.00,'2026-03-26',6);
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'','','987216670','otro','cotizado','2026-03-23') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','','2026-03-23');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'','','995686764','otro','cotizado','2026-03-23') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','','2026-03-23');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'','','992481461','otro','prospecto','2026-03-23') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','','2026-03-23');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Carlos','Céspedes','992381228','otro','cotizado','2026-03-23') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','envio_cotizacion','Maternidad','2026-03-23');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Jeimy','','985594358','otro','cotizado','2026-03-23') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','envio_cotizacion','Familia 4','2026-03-23');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Isidoro','','976539479','otro','prospecto','2026-03-25') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','','2026-03-25');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Mirian','Beatriz','992071644','otro','cotizado','2026-03-25') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','envio_cotizacion','Individuales','2026-03-25');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'','','994239023','otro','prospecto','2026-03-25') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','','2026-03-25');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Javier','Bernal','992407021','otro','cotizado','2026-03-25') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','envio_cotizacion','Envió opciones','2026-03-25');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Alexandra','Pratt','984681521','otro','cotizado','2026-03-25') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','envio_cotizacion','Pareja','2026-03-25');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Patricia','','991859425','otro','prospecto','2026-03-25') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','','2026-03-25');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Sonia','Pérez','992419064','otro','prospecto','2026-03-26') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','','2026-03-26');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'','','981244148','otro','prospecto','2026-03-27') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','','2026-03-27');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'','','981983191','otro','prospecto','2026-03-27') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','contacto_inicial','','2026-03-27');
  INSERT INTO clients (org_id,agent_id,first_name,last_name,phone,preferred_channel,status,last_contact_at) VALUES (v_org,v_adm,'Alberto','Irala','987130021','otro','cotizado','2026-03-27') RETURNING id INTO c; INSERT INTO activities (org_id,client_id,agent_id,channel,activity_type,message,created_at) VALUES (v_org,c,v_adm,'otro','envio_cotizacion','Envió opciones','2026-03-27');
END $$;
